services:
  backend:
    container_name: backend
    platform: linux/amd64
    build:
      #context - exactly this file (in this case the root map)
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    #host to container
    ports:
      - "8000:8000"
    image: ${ACR_SERVER_LOGIN}/backend:${IMAGE_TAG:-latest}

  frontend:
    container_name: frontend
    platform: linux/amd64
    build:
      #context - exactly this file (in this case the root map)
      context: .
      dockerfile: dockerfiles/frontend.dockerfile
    #host to container
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: http://backend:8000/eclipse
    image: ${ACR_SERVER_LOGIN}/frontend:${IMAGE_TAG:-latest}